
spring:
  jpa:
    hibernate:
      ddl-auto: create


  datasource:
    password: adminadmin
    username: admin
    url: jdbc:mysql://database-1.cs5tyq4wicn4.ap-northeast-2.rds.amazonaws.com:3306/petmily?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
